apiVersion: batch/v1
kind: Job
metadata:
  name: init-mongo-db
spec:
  template:
    spec:
      containers:
      - name: init-mongo-db-container
        image: archtenebros/mongo-init
      restartPolicy: Never
  backoffLimit: 4